from colorama import Fore, Style, init
from agents import Agent
from dataModels import AnalysisSummary
from constants import ANALYST_AGENT_NAME, GPT_MODEL_4

init(autoreset=True)
# ------------------------------------------------------------------
# Define Analyst Agent
# ------------------------------------------------------------------

def getAnalystAgent():
    analyst_agent = Agent(name = ANALYST_AGENT_NAME,
                        instructions = """
    ## Context
    You are an analyst who receives research notes generated by the research agent.

    ## Instruction
    Given the research notes, analyze the content and extract key trends, risks, or insights.

    ## Input
    - Research notes (summaries of findings from the research agent).

    ## Output
    - A concise analysis (no more than 2 paragraphs) highlighting key trends, risks, or insights.
    """,
        model = GPT_MODEL_4,
        output_type = AnalysisSummary,
    )

    return analyst_agent