import os, requests, asyncio
from colorama import Fore, Style, init
from dotenv import load_dotenv
from openai import OpenAI
from agents import Agent, Runner, function_tool, SQLiteSession
from typing_extensions import TypedDict
from pydantic import BaseModel

# ------------------------------------------------------------------
# Load environment variables and initialize colorama
# ------------------------------------------------------------------
load_dotenv()
init(autoreset=True)

openai_api_key = os.getenv("OPENAI_API_KEY")
tavily_api_key = os.getenv("TAVILY_API_KEY")

if not openai_api_key or not tavily_api_key:
    raise ValueError(f"{Fore.RED}1️⃣ OPENAI_API_KEY or TAVILY_API_KEY not found in environment variables. ❌ {Style.RESET_ALL}")

print(f""" 
{Fore.GREEN}
 -----------------------------------
  1️⃣  Environment successfully loaded. ✅{Style.RESET_ALL}
""")

# ------------------------------------------------------------------
# Define data models for tool input and output
# ------------------------------------------------------------------

class TavilySearchParams(TypedDict):
    query: str
    max_results: int

class AnalysisSummary(BaseModel):
    summary: str

class FinalReport(BaseModel):
    short_summary: str  # A brief 2–3 sentence executive summary
    markdown_report: str    # A detailed report in Markdown format (at least 500 words)
    follow_up_questions: list[str]    # A list of 3–5 suggested follow-up research questions

# ------------------------------------------------------------------
# Define the Tavily search tool
# ------------------------------------------------------------------

@function_tool
def tavily_search(params: TavilySearchParams) -> str:

    url = "https://api.tavily.com/search"
    headers = {"Content-Type": "application/json"}
    payload = {
        "api_key": tavily_api_key,
        "query": params["query"],
        "max_results": params.get("max_results", 3),
    }

    response = requests.post(url, json = payload, headers = headers)
    if response.status_code == 200:
        results = response.json().get("results", [])
        summary = "\n".join([f"- {r['title']}: {r['content']}" for r in results])
        return summary if summary else "No relevant results found."
    else:
        return f"Tavily API error: {response.status_code}"

print(f""" {Fore.GREEN}  2️⃣ Tavily search tool ready ✅ """)

# ------------------------------------------------------------------
# Define the Researcher Agent
# ------------------------------------------------------------------

researcher_agent = Agent(name = "Researcher",
                         instructions = """
## Context
You are a research agent with access to the Tavily search tool.

## Instruction
Given a user query, use the Tavily search tool to find relevant information and summarize the key findings.

## Input
- A research query from the user.

## Output
- A summary of key findings in a maximum of 5 bullet points.
""",
    model = "gpt-4.1-mini",
    tools = [tavily_search],
    output_type = AnalysisSummary)

print(f""" {Fore.GREEN} 3️⃣  Researcher AI agent is now ready ✅ """)

# ------------------------------------------------------------------
# Define Analyst Agent
# ------------------------------------------------------------------
analyst_agent = Agent(name = "Analyst",
                      instructions = """
## Context
You are an analyst who receives research notes generated by the research agent.

## Instruction
Given the research notes, analyze the content and extract key trends, risks, or insights.

## Input
- Research notes (summaries of findings from the research agent).

## Output
- A concise analysis (no more than 2 paragraphs) highlighting key trends, risks, or insights.
""",
    model = "gpt-4.1-mini",
    output_type = AnalysisSummary,
)

print(f""" {Fore.GREEN} 4️⃣  Analyst AI agent is now ready ✅ {Style.RESET_ALL}""")

# ------------------------------------------------------------------
# Define Writer Agent
# ------------------------------------------------------------------
writer_agent = Agent(
    name = "Writer",
    instructions = """
You are a senior market analyst tasked with generating an executive-level research report.

## Context
You will receive:
- The original user query (the research question or topic of interest).
- Summaries and analyses generated by helper tools: 'researcher_agent' (for bullet-point research findings) and 'analyst_agent' (for key trends, risks, or insights).

You may call these helper tools as needed to gather additional information or clarify findings.

## Instructions
Your job is to synthesize all available information and produce the following outputs:
1. **Executive Summary:** Write a concise summary (2–3 sentences) highlighting the most important findings relevant to the original query.
2. **Detailed Markdown Report:** Compose a comprehensive, well-structured report in markdown format (at least 500 words) that covers key findings, context, implications, and supporting evidence.
3. **Follow-up Research Questions:** Suggest 3–5 thoughtful follow-up questions for further investigation.

## Input
- The original user query.
- Summaries and analyses from the helper tools.

## Output
Return a structured object with:
- `short_summary`: The executive summary.
- `markdown_report`: The detailed markdown report.
- `follow_up_questions`: A list of 3–5 follow-up research questions.
""",
    model = "gpt-4.1-mini",
    output_type = FinalReport,
)

print(f""" {Fore.GREEN} 5️⃣  Writer AI agent is now ready ✅ {Style.RESET_ALL}""")

# ------------------------------------------------------------------
# Main function to run the agent
# ------------------------------------------------------------------
session = SQLiteSession("research_agent_practice")
async def main(user_query: str):
    try:
        # Step 1: Run the researcher agent to gather information about the user's query
        researcher_result = await Runner.run(researcher_agent, user_query, session = session)
        research_summary = researcher_result.final_output.summary  # Get the short research summary

        # Step 2: Run the analyst agent to analyze the research findings
        analyst_result = await Runner.run(analyst_agent, research_summary, session = session)
        analysis_summary = analyst_result.final_output.summary  # Get the short analysis summary

        # Step 3: Prepare the combined input for the writer agent
        input_for_writer = (
            f"Original query: {user_query}\n"
            f"Research summary: {research_summary}\n"
            f"Analysis summary: {analysis_summary}"
        )

        # Step 4: Run the writer agent to create the final report
        writer_result = await Runner.run(writer_agent, input_for_writer, session = session)
        final_output: FinalReport = writer_result.final_output  # The final report from the writer

        # Step 5: Display the results in a nice, clear format
        print(f"---")
        print(f"### 📝 **Short Summary:**\n{final_output.short_summary}")  # Quick overview
        print(f"\n\n-----------------\n\n")
        print(f"### 📄 **Full Report (Markdown):**\n{final_output.markdown_report}")  # Detailed report
        print(f"\n\n-----------------\n\n")
        print(

            "### 🔍 **Follow-Up Questions:**\n- "
            + "\n- ".join(final_output.follow_up_questions)  # Any extra questions the user might explore
        )
        print(f"\n\n-----------------\n\n")
    except Exception as e:
        print(f"❌  {Fore.RED}Error: {str(e)}{Style.RESET_ALL}")

# ------------------------------------------------------------------
# Run the main function
# ------------------------------------------------------------------

if __name__ == "__main__":
    try:
        print(f""" {Fore.CYAN}
                --------------------------------------------------------------------------------------------------
                 🙋🏻‍♂️ Welcome to the Research Agent! All agents are set up! ✅ 
                --------------------------------------------------------------------------------------------------{Style.RESET_ALL}
            """)
        while True:
            user_query = input(f"{Fore.YELLOW}Enter your research query (or type 'exit' to quit): {Style.RESET_ALL}")
            if user_query.lower() == "exit":
                print(f"{Fore.CYAN}Exiting the Research Agent. Goodbye! 👋{Style.RESET_ALL}")
                break
            if not user_query.strip():
                print(f"{Fore.RED}Please enter a valid query. ❌{Style.RESET_ALL}")
                continue
            
            asyncio.run(main(user_query))
    except Exception as e:
        print(f"❌  {Fore.RED}Error: {str(e)}{Style.RESET_ALL}")