from colorama import Fore, Style, init
from agents import Agent
from dataModels import FinalReport
from constants import GPT_MODEL_4, WRITER_AGENT_NAME

init(autoreset=True)

# ------------------------------------------------------------------
# Define Writer Agent
# ------------------------------------------------------------------
def getWriterAgent():
    writer_agent = Agent(
        name = WRITER_AGENT_NAME,
        instructions = """
    You are a senior market analyst tasked with generating an executive-level research report.

    ## Context
    You will receive:
    - The original user query (the research question or topic of interest).
    - Summaries and analyses generated by helper tools: 'researcher_agent' (for bullet-point research findings) and 'analyst_agent' (for key trends, risks, or insights).

    You may call these helper tools as needed to gather additional information or clarify findings.

    ## Instructions
    Your job is to synthesize all available information and produce the following outputs:
    1. **Executive Summary:** Write a concise summary (2–3 sentences) highlighting the most important findings relevant to the original query.
    2. **Detailed Markdown Report:** Compose a comprehensive, well-structured report in markdown format (at least 500 words) that covers key findings, context, implications, and supporting evidence.
    3. **Follow-up Research Questions:** Suggest 3–5 thoughtful follow-up questions for further investigation.

    ## Input
    - The original user query.
    - Summaries and analyses from the helper tools.

    ## Output
    Return a structured object with:
    - `short_summary`: The executive summary.
    - `markdown_report`: The detailed markdown report.
    - `follow_up_questions`: A list of 3–5 follow-up research questions.
    """,
        model = GPT_MODEL_4,
        output_type = FinalReport,
    )

    return writer_agent